spring.application.name=ecommerce-api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.profiles.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${var_email}
spring.mail.password=${var+password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

dominio.openapi.prod-uri=http://www.meudominio.com.br

dominio.openapi.dev-uri=http://localhost:8080