spring.application.name=ecommerce-api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.profiles.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=sua_senha_de_aplicativo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true