spring.application.name=ecommerce-api
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${var_email}
spring.mail.password=${var_senha}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.security.token.secret=1234567891011121314151617181920212223242526272829303132
api.security.token.expiration-ms=1200000